### PR TITLE
Update index.html to fix tutorial

### PR DESCRIPTION
**Pull request by words2708**
Fix in index.html to let the tutorial run smoothly from step#5 and reflect the javascript changes henceforth to come through when a user tries out .

### CODE REVIEW

**Comment by words2708** [comment]
I signed the CLA!

**Comment by nicolasgarnier** [comment]
Thanks for the PR @words2708
However the `hidden` attribute on the "sign-in" button is supposed to be there. It should be automatically removed when the user is detected as signed-out. See: https://github.com/firebase/friendlychat-web/blob/master/web/scripts/main.js#L204

This will be triggered just after you update the first function (`initFirebase`) on Step 6.

**Comment by words2708** [comment]
Hi Nicholas,
Thank you for reviewing my PR. Unfortunately the automatic things happen in
step 6 only after this change in tutorial happened. Just fyi. If there's
some other fix that gets us around this, then am happy to take that as
well. Just shared a workaround that helped me get through this issue.

Best,
Words2708

**Comment by nicolasgarnier** [comment]
Hey @words2708 

The thing is on Step 5 the Sign in button is not supposed to show up yet. The text and the screenshot are pretty explicit about it:

image

Is there some text that could have caused confusion to you? Always looking for ways to make the codelab clearer!

**Comment by words2708** [comment]
My Mistake in pointing out the step number. It is at the end of step#6 that one does not see the changes of sign in button & sign out button, without my workaround.

**Comment by nicolasgarnier** [comment]
At the end of step 6 the button should have been automatically displayed because of [main.js#L204](https://github.com/firebase/friendlychat-web/blob/master/web/scripts/main.js#L203-L204):

```js
    // Show sign-in button.
    this.signInButton.removeAttribute('hidden');
```

Can you just make sure that your code looks like the code in the [final project](https://github.com/firebase/friendlychat-web/blob/master/web/scripts/main.js)?
especially the `FriendlyChat.prototype.onAuthStateChanged` method which should [look like this](https://github.com/firebase/friendlychat-web/blob/master/web/scripts/main.js#L174-L206):

```js
// Triggers when the auth state change for instance when the user signs-in or signs-out.
FriendlyChat.prototype.onAuthStateChanged = function(user) {
  if (user) { // User is signed in!
    // Get profile pic and user's name from the Firebase user object.
    var profilePicUrl = user.photoURL;
    var userName = user.displayName;

    // Set the user's profile pic and name.
    this.userPic.style.backgroundImage = 'url(' + (profilePicUrl || '/images/profile_placeholder.png') + ')';
    this.userName.textContent = userName;

    // Show user's profile and sign-out button.
    this.userName.removeAttribute('hidden');
    this.userPic.removeAttribute('hidden');
    this.signOutButton.removeAttribute('hidden');

    // Hide sign-in button.
    this.signInButton.setAttribute('hidden', 'true');

    // We load currently existing chant messages.
    this.loadMessages();

    // We save the Firebase Messaging Device token and enable notifications.
    this.saveMessagingDeviceToken();
  } else { // User is signed out!
    // Hide user's profile and sign-out button.
    this.userName.setAttribute('hidden', 'true');
    this.userPic.setAttribute('hidden', 'true');
    this.signOutButton.setAttribute('hidden', 'true');

    // Show sign-in button.
    this.signInButton.removeAttribute('hidden');
  }
};
```

Alternatively you could deploy your code online and I could have a look :)

**Comment by words2708** [comment]
https://github.com/words2708/friendlychat-web/tree/patch-1/web-start/scripts/main.js has the code that reflects the final project.

**Comment by words2708** [comment]
https://words2708-firebase-project.firebaseapp.com is where I've deployed this code.

**Comment by nicolasgarnier** [comment]
So if you add back the two "hidden" attributes to the HTML, things should still work the same no? (could you please add these attribute and re-deploy).

Another question: which browser are you using?

**Comment by words2708** [comment]
Browser: Chrome
Cannot reproduce issue now that I have made changes to the project with all goodness. Somehow it feels this issue is not 100% reproducible but something with the sign-in signout button code needs to be looked at. For timebeing ill keep this change only local and not post it formally. Does that sound fair?

If we agree, I'll close the pull request

**Comment by words2708** [comment]
Also more data not sure if its relevant: I had originally repurposed a project. when I created a fresh project and unzipped the contents of tutorial into a new directory, I did not have the same issue. Again this issue is not being reproducible 100%. I'm sure I had trouble the first time and only change that helped was index.html to reveal the sign-in/sign-out button code's effect. 

That's it from me.

**Pull request closed without merging**
