### PR TITLE
all of react 16.8 almost

### PR DESCRIPTION
**Pull request by MichaelRCruz**
Hey, hoping you all could find this useful. I thought it was a good time to share since the new Firebase extensions are exactly what I need for my traffic and presence systems. This app is as basic as I could get it. This means only React and Firebase, iirc. Apologies if this needs to be done on a different node.

Love,
Michael

### CODE REVIEW

**Comment by MichaelRCruz** [comment]
If it helps to go over the features, I'd like to list a few.

0. Multi oauth strategies for a unified user config (including dynamic link auth)
1. user presence system (buggy, but the new extension should fix that)
2. fully isolated components, i.e., not effected by parent redraw.
3. Context, Hooks
4. vanilla css and fully responsive
5. no redux
6. push notifications (didn't have ios cert at time so turned off)
7. supports markdown (using lib)
8. form validation including real-time namespace availability (never turned that back on after refactor)
9. a little verbose in parts, but was intended for special reasons, will fix

**Comment by jhuleatt** [comment]
Hi @MichaelRCruz, wow, this is a really fully featured app! While it is super awesome, it's too complex for us to take on the responsibility of maintaining it in this repo. 

If you're willing to create your own repo for this, you can get it listed on https://firebaseopensource.com/ by submitting an issue [here](https://github.com/firebase/firebaseopensource.com/issues/new?template=new_project.md). 

Thanks again for putting this together, and sorry we can't keep it here.

As a side note, since you have experience integrating with React's new features, I'd love to hear your feedback on [this library I've been working on](https://github.com/FirebaseExtended/reactfire).

**Comment by MichaelRCruz** [comment]
@jhuleatt Thanks for the direction! Also, I'm scratching my head as to how I never came across your project. Great work!

This reminds me of that movie, Contact, when the movie's big surprise was the revelation that there was an entirely different space traveling portal built with the same technology after the first was destroyed by the antagonist. lol

**Comment by samtstern** [comment]
@MichaelRCruz no spoilers!!!! :-)

**Comment by MichaelRCruz** [comment]
@samtstern btw, I forked your saying if that's okay with you.

**Pull request closed without merging**
