### PR TITLE
Create complete project for Firebase Performance Monitoring

### PR DESCRIPTION
**Pull request by zijianjoy**
Codelab under construction: https://docs.google.com/document/d/1YUEtkFl6u1szNNfuv22XVL3ommxV2l_WglPWFhQ_5Eo/edit#heading=h.7sa4zxkhmsum

### CODE REVIEW

**Comment by samtstern** [comment]
@zijianjoy did you maybe mean to send this PR to https://github.com/firebase/quickstart-js ?  Or is this project somehow part of the "FriendlyChat" codelab?

**Comment by kroikie** [comment]
@JeffAtGoog @zijianjoy could we add this as a step in the current codelab. Somewhere after sending images should work well.

**Comment by zijianjoy** [comment]
> @zijianjoy did you maybe mean to send this PR to https://github.com/firebase/quickstart-js ? Or is this project somehow part of the "FriendlyChat" codelab?

We want to create a new codelab for Performance Monitoring based on Friendlychat.

**Comment by zijianjoy** [comment]
> @JeffAtGoog @zijianjoy could we add this as a step in the current codelab. Somewhere after sending images should work well.

We want to have a deepdive for Performance Monitoring and introduce features we provide in detail. Here is the codelab under construction: go/fireperf-web-codelab

**Comment by kroikie** [comment]
@zijianjoy sounds good, an additional step for the existing codelab with default traces and more advanced ones in the perf sepcific codelab based on the completed friendly chat app.

**Comment by zijianjoy** [comment]
> @zijianjoy sounds good, an additional step for the existing codelab with default traces and more advanced ones in the perf sepcific codelab based on the completed friendly chat app.

Thank you!

**Comment by jhuleatt** [comment]
I ran through the codelab draft with the `performance-monitoring-start` directory and it worked. I also confirmed that the `performance-monitoring` directory works.

**Comment by jhuleatt** [comment]
@zijianjoy did you also want to add a step to the main codelab in this PR? Or are you saving that for another one?

**Comment by jhuleatt** [comment]
(we talked offline and the main codelab changes will go into another PR)

**Pull request merged**
